# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `transportation`")
spark.sql("USE SCHEMA `bronze`")

# COMMAND ----------

display(spark.sql("SELECT COUNT(DISTINCT payment_id) FROM transportation.bronze.online_bronze"))

# COMMAND ----------

display(spark.sql("SELECT COUNT(DISTINCT Order_ID) FROM transportation.bronze.online_bronze"))

# COMMAND ----------

display(spark.sql("SELECT DISTINCT store_country FROM transportation.bronze.offline_bronze"))

# COMMAND ----------

display(spark.sql("SELECT country, Region,State,City FROM transportation.bronze.online_bronze"))

# COMMAND ----------

display(spark.sql("SELECT DISTINCT  store_region   FROM transportation.bronze.offline_bronze"))

# COMMAND ----------

display(spark.sql("SELECT DISTINCT  payment_provider  FROM transportation.bronze.offline_bronze"))

# COMMAND ----------

display(spark.sql("SELECT DISTINCT customer_name, customer_surname, city FROM transportation.bronze.online_bronze"))

# COMMAND ----------

display(spark.sql("SELECT customer_name, customer_surname, city FROM transportation.bronze.online_bronze WHERE customer_name = 'Thomas' and customer_surname = 'Thornton'"))